name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build Package for AWS Lambda
      # You may pin to the exact commit or the version.
      # uses: sevco/go-lambda-action@9e66f05f48818d2062a49cfb3341488b671899ea
      uses: sevco/go-lambda-action@v3.0.1
      with:
        files: "gameBuzzerHandler.go"
        # Git credentials - https://git-scm.com/docs/git-credential-store
        credentials: ${{ secrets.GIT_CREDENTIALS }}
    - name: Deploy AWS Lambda function
      uses: yvesgurcan/deploy-lambda-function@v0.0.5
      with:
        package: "build/artifacts/gameBuzzerHandler.main.latest.zip"
        function-name: "gameBuzzerHandler"
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_SECRET_ID: ${{ secrets.AWS_SECRET_ID }}
        AWS_REGION: "us-east-2"
